class IsolatorConstants:
    WIDTH_HEIGHT_RATIO_MIN = 0.31
    WIDTH_HEIGHT_RATIO_MAX = 0.75

    PIXEL_RATIO_MIN = 25
    PIXEL_RATIO_MAX = 75

    ADDITION_MEAN = 45

    THRESHOLD_LOWER = 20
    THRESHOLD_UPPER = 200
