class IsolatorConstants:
    WIDTH_HEIGHT_RATIO_MIN = 0.35
    WIDTH_HEIGHT_RATIO_MAX = 0.75

    PIXEL_RATIO_MIN = 30
    PIXEL_RATIO_MAX = 75

    ADDITION_MEAN = 30

    THRESHOLD_LOWER = 20
    THRESHOLD_UPPER = 200
